service_now:
  instance_name: "dev73771"
  user_name: "admin"
  password: "aFmS0QYUyq9l"
  table_name: "incident"

workflow:
  incident_group_key_field: "prometheus_alertgroup_id"
  no_update_states: [7,8]
  incident_update_fields: ["comments"]

default_incident:
  assignment_group: "{{.CommonAnnotations.assignment_group}}"
  category: "Failure"
  cmdb_ci: "{{.CommonAnnotations.cmdb_ci}}"
  comments: "Alerts list:\n\n{{ range .Alerts }}[{{ .Status }}] {{.StartsAt}} {{.Labels.alertname}}\n{{.Annotations.description}}\n\n{{ end }}"
  company: "{{.CommonAnnotations.company}}"
  contact_type : "{{.CommonAnnotations.contact_type}}"
  description: "Received alerts from AlertManager at {{.ExternalURL}} (\"{{.Receiver}}\" receiver configuration) with common descriptions:\n\n{{.CommonAnnotations.description}}"
  impact: "2"
  short_description: "Alerts from group: {{ range $key, $val := .GroupLabels}}{{ $key }}:{{ $val }} {{end}}"
  subcategory: "Missing Part"
  urgency: "{{.CommonAnnotations.urgency}}"
